### ISSUE TITLE
Issues with the testenvironment at vipps

### ISSUE THREAD

**Issue by tofiksa** [vippsas/vipps-login-api#36]
Hi guys,

since yesterday I only seem to get "error=server_error&error_description=Something+went+wrong%2C+please+try+again" each time I try to authenticate via vipps-login api using the endpoint https://apitest.vipps.no/access-management-1.0/access/oauth2/auth. The redirect to the callback uri works fine, but i dont get the code parameter from url queryparameter so I can get my accesstoken from the token endpoint. This worked fine during last weekend, but not as of yesterday.

**Comment by VidarHolm** [comment]
Hi. There was an issue in our test environment. This have now been fixed and you should be able to login as before. Sorry for the inconvenience

Best regards
Vidar

**Comment by tofiksa** [comment]
thank you for the information, is there a "status page" somewhere that I could follow or receive announcements for downtime?

**Comment by VidarHolm** [comment]
Hi.

We have two status pages where you also can set up subscriptions:
Production: https://vipps.statuspage.io
Test: https://vipps-test.statuspage.io

The problems you experienced earlier this week would however most likely not be visible here since it was a bug effecting only some scenarios.

Regards
Vidar
